WIP: Create legacy audioscrobbler API
krateng/maloja pull request #37
Opened 2020-10-01 20:03 UTC by ICTman1076

**Do not merge,** work in progress.

2020-10-01 20:05 UTC, ICTman1076 commented on maloja/apis/legacy_audioscrobber.py
> +					protocol + "://"+domain+":"+port+"/apis/legacyaudioscrobbler/scrobble" + "\n"
I'm not quite sure how to get the protocol, domain and port of requests from nimrodel, so I placed placeholder variables to show where they are supposed to go

2020-10-01 20:46 UTC, ICTman1076 commented on maloja/apis/legacy_audioscrobber.py
> +					protocol + "://"+domain+":"+port+"/apis/legacyaudioscrobbler/scrobble" + "\n"
One idea I had is getting all this information through the otherwise redundant username, but a more elegant and hidden solution would be nice

2020-10-01 23:05 UTC, p182 requested changes
Fix typo in filename legacy_audioscrobb*l*er (letter "l" after "bb")

2020-10-02 02:33 UTC, krateng commented
Since the use case for this protocol is gonna be very limited, I think it would be an acceptable option to just have the user specify their public url in the settings - but the `Host` header should be available as part of the keys that are passed to the function (the second argument of self.handle).

2020-10-02 02:36 UTC, krateng commented on maloja/apis/legacy_audioscrobber.py
> +					protocol + "://"+domain+":"+port+"/apis/legacyaudioscrobbler/scrobble" + "\n"
Don't have time to test it now, but I added a line to get the host from the HTTP header, check if you can use that

2020-10-03 18:16 UTC, ICTman1076 commented
Thanks - I'm having trouble getting it set up for testing since I don't currently have access to a Linux machine (maloja tries to find Linux environment variables that don't exist on windows) but I'll push my code as soon as i can

2020-10-29 16:23 UTC, merged